# -*- coding: utf-8 -*-
"""TUGAS2_KEL10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q5pikzhVMQVBzqHMArYKwVbrBwUIhQW_
"""

import pandas as pd
import requests
from io import StringIO

from google.colab import drive
drive.mount('/content/drive')

link_bus_sekolah = {
    '2017': {
        'Januari': '/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-januari-2017(1).csv',
        'Februari':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-februari-2017.csv',
        'Maret':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-maret-2017.csv',
        'April':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-april-2017.csv',
        'Mei':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-mei-2017.csv',
        'Juni':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-juni-2017.csv',
        'Juli':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-juli-2017.csv',
        'Agustus':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-agustus-2017.csv',
        'September':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-september-2017.csv',
        'Oktober':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-oktober-2017.csv',
        'November':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-november-2017.csv',
        'Desember':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2017/penumpang-bus-sekolah-desember-2017.csv'
             },
    '2018': {
        'Januari': '/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-januari-2018.csv',
        'Februari':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-februari-2018.csv',
        'Maret':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-maret-2018.csv',
        'April':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-april-2018.csv',
        'Mei':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-mei-2018.csv',
        'Juni':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-juni-2018.csv',
        'Juli':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-juli-2018.csv',
        'Agustus':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-agustus-2018.csv',
        'September':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-september-2018.csv',
        'Oktober':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-oktober-2018.csv',
        'November':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-november-2018.csv',
        'Desember':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2018/data-penumpang-bus-sekolah-desember-2018.csv'
            },
    '2019':{
        'Januari': '/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-januari-2019.csv',
        'Februari':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-februari-2019.csv',
        'Maret':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-maret-2019.csv',
        'April':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-april-2019.csv',
        'Mei':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-mei-2019.csv',
        'Juni':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-juni-2019.csv',
        'Juli':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-juli-2019.csv',
        'Agustus':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-agustus-2019.csv',
        'September':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-september-2019.csv',
        'Oktober':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-oktober-2019.csv',
        'November':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-november-2019.csv',
        'Desember':'/content/drive/MyDrive/Dibimbing/Tugas_Python2/2019/data-penumpang-bus-sekolah-desember-2019.csv'
            }
}

df_bus_sekolah_all = pd.DataFrame()

for tahun, bulan_dict in link_bus_sekolah.items():
    for bulan, file_path in bulan_dict.items():
        try:
            # Baca file CSV dengan encoding 'latin-1'
            df = pd.read_csv(file_path, encoding='latin-1')
            df['Tahun'] = tahun
            df['Bulan'] = bulan
            # Gabungkan DataFrame ke dalam DataFrame utama
            df_bus_sekolah_all = pd.concat([df_bus_sekolah_all, df], ignore_index=True)
        except Exception as e:
            print(f'Error: {e}')

# Tampilkan DataFrame hasil penggabungan
print(df_bus_sekolah_all)

df_bus_sekolah_all

df_bus_sekolah_all.drop(['Unnamed: 5','ritase'], axis=1).head()

df_cleaned = df_bus_sekolah_all.dropna()

df.isna().sum()

df_bus_sekolah_all.info()

a=df_bus_sekolah_all.dropna(subset=['jumlah_bus'])
a

b=a.dropna(subset=['jumlah_penumpang'])
b

b.info()

def konversi_angka(b):
  jumlah_bus = b['jumlah_bus']
  jumlah_penumpang = b['jumlah_penumpang']
  if str(jumlah_penumpang) != 'nan':
    jumlah_penumpang = int(str(jumlah_penumpang).replace('.', '').replace('.', ''))
  if str(jumlah_bus) != 'nan':
    jumlah_bus = int(str(jumlah_bus).replace(',', '').replace('.', ''))
  return pd.Series({'jumlah_bus': jumlah_bus, 'jumlah_penumpang': jumlah_penumpang})

b

b.info()

b['jumlah_bus'] = b['jumlah_bus'].astype(int)

b

def ChangeType(x):
  if isinstance(x,str):
    d= x.replace(',','')
    e= float(d)
    f= int(e)
  else:
    f= int(x)
  return f

b['jumlah_penumpang'] = b['jumlah_penumpang'].apply(ChangeType)

b

z = b.groupby('Tahun').agg(
    sum_jumlah_bus = ('jumlah_bus','sum'),
    mean_jumlah_bus = ('jumlah_bus','mean'),
    max_jumlah_bus = ('jumlah_bus','max'),
    sum_jumlah_penumpang = ('jumlah_penumpang','sum'),
    mean_jumlah_penumpang = ('jumlah_penumpang','mean'),
    max_jumlah_penumpang = ('jumlah_penumpang','max')
)

z

z.to_json(r'D:\Bismillah\Buku.json')